// Current_React/app/components/SettingComponent/index.js
/**
*
* SettingComponent
*
*/

import React from 'react';

class SettingComponent extends React.Component {
  constructor (props) {
    super(props)
    const {
      currentUser: { email, bio, image, username }
    } = props
    this.state = {
      email,
      bio,
      image,
      username,
      password: ''
    }
  }

  onChangeImage = (evt) => {
    this.setState({ image: evt.target.value})
  }

  onChangeUsername = (evt) => {
    this.setState({ username: evt.target.value})
  }

  onChangeBio = (evt) => {
    this.setState({ bio: evt.target.value})
  }

  onChangeEmail = (evt) => {
    this.setState({ email: evt.target.value})
  }

  onChangePassword = (evt) => {
    this.setState({ password: evt.target.value})
  }

  handleSubmit = (evt) => {
    evt.preventDefault();

    this.props.settingProfile(this.state)
  }

  render() {
    const {
      email,
      bio,
      image,
      username
    } = this.state
    return (
      <div className = "settings-page">
        <div className = "container page">
          <div className = "row">

            <div className = "col-md-6 offset-md-3 col-xs-12">
              <h1 className = "text-xs-center">Your Settings</h1>

              <form onSubmit = { this.handleSubmit }>
                <fieldset>
                    <fieldset className = "form-group">
                      <input
                        className = "form-control"
                        type="text"
                        placeholder="URL of profile picture"
                        value = { image }
                        onChange = { this.onChangeImage }
                      />
                    </fieldset>
                    <fieldset className = "form-group">
                      <input
                        className = "form-control form-control-lg"
                        type="text"
                        placeholder="Your Name"
                        onChange = { this.onChangeUsername }
                        value = { username }
                      />
                    </fieldset>
                    <fieldset className = "form-group">
                      <textarea
                        className = "form-control form-control-lg"
                        rows="8"
                        placeholder="Short bio about you"
                        onChange = { this.onChangeBio }
                        value = { bio }
                      ></textarea>
                    </fieldset>
                    <fieldset className = "form-group">
                      <input
                        className = "form-control form-control-lg"
                        type="text"
                        placeholder="Email"
                        onChange = { this.onChangeEmail }
                        value = { email }
                      />
                    </fieldset>
                    <fieldset className = "form-group">
                      <input
                        className = "form-control form-control-lg"
                        type="password"
                        placeholder="Password"
                        onChange = { this.onChangePassword }
                      />
                    </fieldset>
                    <button
                      className = "btn btn-lg btn-primary pull-xs-right"
                      type = "submit"
                    >
                      Update Settings
                    </button>
                </fieldset>
              </form>
            </div>

          </div>
        </div>
      </div>
    );
  }
}

SettingComponent.propTypes = {

};

export default SettingComponent;

// Current Angular/src/app/setting/setting.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

import { userService } from '../core/services';

@Component({
  selector: 'app-setting',
  templateUrl: './setting.component.html',
  styleUrls: ['./setting.component.css']
})
export class SettingComponent implements OnInit {
  form : FormGroup;
  public user: object = {};

  constructor(
    private fb: FormBuilder,
    private userService: userService
  ) {
    this.form = this.fb.group({
      image: '',
      username: '',
      bio: '',
      email: '',
      password: ''
    });
   }

  ngOnInit() {
    this.userService.currentDataUser.subscribe((res) => {
      Object.assign(this.user, res)
      this.form.patchValue(res)
    })
  }

  handleSubmit () {
    Object.assign(this.user, this.form.value)

    this.userService.updateUser({ user: this.user})
      .subscribe((res) => {

      })
  }
}

<div class="settings-page">
    <div class="container page">
      <div class="row">
        <div class="col-md-6 offset-md-3 col-xs-12">

          <h1 class="text-xs-center">Your Settings</h1>

          <!-- <app-list-errors [errors]="errors"></app-list-errors> -->

          <form [formGroup] = "form" (ngSubmit) = "handleSubmit()">
            <fieldset>

              <fieldset class="form-group">
                <input class="form-control"
                  type="text"
                  placeholder="URL of profile picture"
                  formControlName="image"
                />
              </fieldset>

              <fieldset class="form-group">
                <input class="form-control form-control-lg"
                  type="text"
                  placeholder="Username"
                  formControlName="username"
                />
              </fieldset>

              <fieldset class="form-group">
                <textarea class="form-control form-control-lg"
                  rows="8"
                  placeholder="Short bio about you"
                  formControlName="bio"
                >
                </textarea>
              </fieldset>

              <fieldset class="form-group">
                <input class="form-control form-control-lg"
                  type="email"
                  placeholder="Email"
                  formControlName="email"
                />
              </fieldset>

              <fieldset class="form-group">
                <input class="form-control form-control-lg"
                  type="password"
                  placeholder="New Password"
                  formControlName="password"
                />
              </fieldset>

              <button class="btn btn-lg btn-primary pull-xs-right"
                type="submit">
                Update Settings
              </button>

            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
